/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 *
 * SOLUTION
 * Generete Fibonacci numbers and test their divisibility by 2. Then sum them up.
 *
 * RESULT: 4613732
 */
package pe_002;

public class PE_002 {

    public static void main(String[] args) {
        long fibonacci1 = 1, fibonacci2 = 2, fibonacci, sum = 2;
        while(fibonacci2 < 4000000){
            fibonacci = fibonacci1 + fibonacci2;
            if(fibonacci % 2 == 0)
                sum = sum + fibonacci;
            fibonacci1 = fibonacci2;
            fibonacci2 = fibonacci;
        }
        System.out.println("Sum: " + sum);
    }
    
}
